__title__ = 'Geo km'
__description__ = 'Calculate distance and travel time between points using API.'
__url__ = 'not available'
__version__ = '1.02'
__author__ = 'Radchenko V., Shkaberda V.'
__author_email__ = 'not available'
__license__ = 'MIT License'
__copyright__ = 'Copyright 2018 Radchenko Vlad, Shkaberda Vadim'